### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by rtritto** [freecycle/swig-templates#16]
```js
import express from 'express'
import swig from 'free-swig'

const app = express()

// cache is false
const swigOptions = {
  cache: process.env.NODE_ENV === 'production' ? 'memory' : false
}

// Swig generates the TypeError
const swigEngine = new swig.Swig(swigOptions)
```

Output
```console
TypeError: Cannot read properties of undefined (reading 'file')
    at Object.eval [as tpl] (eval at precompile (C:\<MY_PROJECT>\node_modules\free-swig\lib\swig.js:539:13), <anonymous>:183:2181)
    at compiled (C:\<MY_PROJECT>\node_modules\free-swig\lib\swig.js:666:18)
    at C:\<MY_PROJECT>\node_modules\free-swig\lib\swig.js:606:20
    at C:\<MY_PROJECT>\node_modules\free-swig\lib\swig.js:737:9
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
```

Related https://github.com/vituum/vituum/issues/52

**Comment by steevhise** [comment]
i don't know enough about Express or Vite to fix this with the time I have. Care to offer a pull request?
you might want to look at this example if you havent already https://github.com/steevhise/free-swig/blob/main/examples/express/server.js

Also, this will likely not be where support for the module happens as I'm not at Freecycle any more. and my replacement there is asleep at the wheel.  check out my fork of it. my latest release comes from there.
https://github.com/steevhise/free-swig

**Comment by rtritto** [comment]
Waiting an answer from https://github.com/vituum/vituum/issues/52 where a plugin for _Vite_ should be created.
We can support or open a PR to _Vituum_.
Some examples: https://github.com/vituum/vituum/tree/main/examples
Next step is maybe to link the _Vite plugin for swig_ in _free-swig_.

**Comment by rtritto** [comment]
No plan to create _Vite plugin_ for _swig_: https://github.com/vituum/vituum/issues/52#issuecomment-2266641962
